package com.ecommerce.demo.views;


import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

import com.ecommerce.demo.model.Person;
import com.ecommerce.demo.controller.PersonController;
import com.ecommerce.demo.model.Business;

public class SignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJPanel
     */
    
    private JPanel userProcessContainer;  
    private Business business;
    private PersonController personController;
    
    public SignUpJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.personController = this.business.getPersonDirectory();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtEmailNo = new javax.swing.JTextField();
        txtPhNo = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnClearAll = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 92, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN UP");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 207, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("FIRST NAME");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 156, 25));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("LAST NAME");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 156, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("USERNAME");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 156, 25));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("PASSWORD");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 156, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("EMAIL ID");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 156, 25));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("PH NO");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 156, 25));
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 143, -1));
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 143, -1));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 143, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 143, -1));
        add(txtEmailNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 143, -1));
        add(txtPhNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 143, -1));

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 143, -1));

        btnClearAll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClearAll.setText("CLEAR ALL");
        btnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllActionPerformed(evt);
            }
        });
        add(btnClearAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 156, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.business.setPersonDirectory(this.personController);
        LoginJPanel panel = new LoginJPanel(userProcessContainer, this.business);
        userProcessContainer.add("LoginJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnBackActionPerformed
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String userName = txtUsername.getText();
        String password = txtPassword.getText();
        String email = txtEmailNo.getText();
        String phNo = txtPhNo.getText();
        if (!firstName.isEmpty() && !lastName.isEmpty() && !userName.isEmpty() && !password.isEmpty() && !email.isEmpty() && !phNo.isEmpty()) {
            if (!this.personController.isUsernameUnique(userName)) {
                JOptionPane.showMessageDialog(this, "Username already exists. Please choose a different username.", "Username Exists", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int id = this.personController.getPersonList().size() + 1;
            String role = "Customer";
            Person person = new Person();
            person.setId(id);
            person.setFirstName(firstName);
            person.setLastName(lastName);
            person.setUserName(userName);
            person.setPassword(password);
            person.setEmail(email);
            person.setPhNo(phNo);
            person.setPersonRole(role);
            this.personController.addNewPerson(person);
            String message = "Person Created!\nID: " + id +
                    "\nFirst Name: " + firstName +
                    "\nLast Name: " + lastName +
                    "\nUsername: " + userName +
                    "\nEmail: " + email +
                    "\nPhone Number: " + phNo;
            JOptionPane.showMessageDialog(this, message, "Person Created", JOptionPane.INFORMATION_MESSAGE);
            clearAllfields();
        } else {
            JOptionPane.showMessageDialog(this, "Please fill in all the required fields.", "Incomplete Information", JOptionPane.WARNING_MESSAGE);
        }   
    }//GEN-LAST:event_btnSubmitActionPerformed
    
   
    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllActionPerformed
        // TODO add your handling code here:
        clearAllfields();
    }//GEN-LAST:event_btnClearAllActionPerformed
    
    public void clearAllfields() {
        txtFirstName.setText("");
        txtLastName.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtEmailNo.setText("");
        txtPhNo.setText("");
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtEmailNo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhNo;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
